let faker= require("faker");


module.exports={
	carte:{
		persona:faker.name.findName(),
		photo:faker.image.avatar(),
		address:faker.address.streetAddress(),
		city:faker.address.city(),
		states:faker.address.state(),
		phone:faker.phone.phoneNumber(),
		mail:faker.internet.email()
	},
	carte2:{
		persona:faker.name.findName(),
		photo:faker.image.avatar(),
		address:faker.address.streetAddress(),
		city:faker.address.city(),
		states:faker.address.state(),
		phone:faker.phone.phoneNumber(),
		mail:faker.internet.email()
	},
	carte3:{
		persona:faker.name.findName(),
		photo:faker.image.avatar(),
		address:faker.address.streetAddress(),
		city:faker.address.city(),
		states:faker.address.state(),
		phone:faker.phone.phoneNumber(),
		mail:faker.internet.email()
	},
	carte4:{
		persona:faker.name.findName(),
		photo:faker.image.avatar(),
		address:faker.address.streetAddress(),
		city:faker.address.city(),
		states:faker.address.state(),
		phone:faker.phone.phoneNumber(),
		mail:faker.internet.email()
	},
	carte5:{
		persona:faker.name.findName(),
		photo:faker.image.avatar(),
		address:faker.address.streetAddress(),
		city:faker.address.city(),
		states:faker.address.state(),
		phone:faker.phone.phoneNumber(),
		mail:faker.internet.email()
	},
	carte6:{
		persona:faker.name.findName(),
		photo:faker.image.avatar(),
		address:faker.address.streetAddress(),
		city:faker.address.city(),
		states:faker.address.state(),
		phone:faker.phone.phoneNumber(),
		mail:faker.internet.email()
	}
};